server:
  port: 8084

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: account_db
    password: account_db
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9098/realms/microbank
#          jwk-set-uri: http://localhost:9098/realms/microbank/protocol/openid-connect/certs

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.microbank.account: debug
    root: info
