networks:
  microbank-network:
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "9098:8080"
    command: [ "start-dev", "--import-realm" ]
    networks:
      - microbank-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # AMQP Port

  maildev:
    image: maildev/maildev
    container_name: maildev-container
    ports:
      - "1025:1025" # SMTP Port
      - "1080:1080" # Web UI Port
    networks:
      - microbank-network

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - microbank-network

  postgres-account-service:
    image: postgres:17-alpine
    container_name: account-db-container
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_service
      POSTGRES_PASSWORD: account_service
    ports:
      - "5432:5432"
    networks:
      - microbank-network

  postgres-keycloak:
    image: postgres:17-alpine
    container_name: keycloak-db-container
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    networks:
      - microbank-network

