server:
  port: 8123

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: account-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/account/**

        - id: transaction-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/transaction/**

        - id: document-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/documents/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/microbank
          jwk-set-uri: http://localhost:9098/realms/microbank/protocol/openid-connect/certs


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug