server:
  port: 8085

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: transaction_db
    password: transaction_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true

logging:
  level:
    root: info
    com.microbank.transaction: debug
